const classContenedor1 = document.getElementById('contenedor1');
const classContenedor2 = document.getElementById('contenedor2');
const classContenedor3 = document.getElementById('contenedor3');
const classContenedor4 = document.getElementById('contenedor4');
// cambiar nombre botones ordenado
const btn1 = document.getElementById('btn1');
const btn2 = document.getElementById('btn2');
const btn3 = document.getElementById('btn3');
const btn4 = document.getElementById('btn4');
const btn5 = document.getElementById('btn5');

const btnh = document.getElementById('btnh');
const btn2km = document.getElementById('btn2km');
const btn5km = document.getElementById('btn5km');
const btn10km = document.getElementById('btn10km');
const notInEggs = document.getElementById('not-in-eggs');

const types = document.getElementById('types');
const bug = document.getElementById('bug');
const dark = document.getElementById('dark');
const dragon = document.getElementById('dragon');
const electric = document.getElementById('electric');
const fairy = document.getElementById('fairy');
const fighting = document.getElementById('fighting');
const fire = document.getElementById('fire');
const flying = document.getElementById('flying');
const ghost = document.getElementById('ghost');
const grass = document.getElementById('grass');
const ground = document.getElementById('ground');
const ice = document.getElementById('ice');
const normal = document.getElementById('normal');
const poison = document.getElementById('poison');
const psychic = document.getElementById('psychic');
const rock = document.getElementById('rock');
const steel = document.getElementById('steel');
const water = document.getElementById('water');

const weakness = document.getElementById('weakness');
const bugw = document.getElementById('bugw');
const darkw = document.getElementById('darkw');
const dragonw = document.getElementById('dragonw');
const electricw = document.getElementById('electricw');
const fairyw = document.getElementById('fairyw');
const fightingw = document.getElementById('fightingw');
const firew = document.getElementById('firew');
const flyingw = document.getElementById('flyingw');
const ghostw = document.getElementById('ghostw');
const grassw = document.getElementById('grassw');
const groundw = document.getElementById('groundw');
const icew = document.getElementById('icew');
const normalw = document.getElementById('normalw');
const poisonw = document.getElementById('poisonw');
const psychicw = document.getElementById('psychicw');
const rockw = document.getElementById('rockw');
const steelw = document.getElementById('steelw');
const waterw = document.getElementById('waterw');

const mouseOver1 = () => {
  classContenedor1.classList.add('animacionVer');
  btn2.classList.add('animacionVer');
  btn3.classList.add('animacionVer');
  btn4.classList.add('animacionVer');
  btn5.classList.add('animacionVer');
};
const mouseOut1 = () => {
  classContenedor1.classList.remove('animacionVer');
  btn2.classList.remove('animacionVer');
  btn3.classList.remove('animacionVer');
  btn4.classList.remove('animacionVer');
  btn5.classList.remove('animacionVer');
};
const mouseOver2 = () => {
  classContenedor2.classList.add('animacionVer');
  btn2km.classList.add('animacionVer');
  btn5km.classList.add('animacionVer');
  btn10km.classList.add('animacionVer');
  notInEggs.classList.add('animacionVer');
};
const mouseOut2 = () => {
  classContenedor2.classList.remove('animacionVer');
  btn2km.classList.remove('animacionVer');
  btn5km.classList.remove('animacionVer');
  btn10km.classList.remove('animacionVer');
  notInEggs.classList.remove('animacionVer');
};
const mouseOver3 = () => {
  classContenedor3.classList.add('animacionVer');
  bug.classList.add('animacionVer');
  dark.classList.add('animacionVer');
  dragon.classList.add('animacionVer');
  electric.classList.add('animacionVer');
  fairy.classList.add('animacionVer');
  fighting.classList.add('animacionVer');
  fire.classList.add('animacionVer');
  flying.classList.add('animacionVer');
  ghost.classList.add('animacionVer');
  grass.classList.add('animacionVer');
  ground.classList.add('animacionVer');
  ice.classList.add('animacionVer');
  normal.classList.add('animacionVer');
  poison.classList.add('animacionVer');
  psychic.classList.add('animacionVer');
  rock.classList.add('animacionVer');
  steel.classList.add('animacionVer');
  water.classList.add('animacionVer');
};
const mouseOut3 = () => {
  classContenedor3.classList.remove('animacionVer');
  bug.classList.remove('animacionVer');
  dark.classList.remove('animacionVer');
  dragon.classList.remove('animacionVer');
  electric.classList.remove('animacionVer');
  fairy.classList.remove('animacionVer');
  fighting.classList.remove('animacionVer');
  fire.classList.remove('animacionVer');
  flying.classList.remove('animacionVer');
  ghost.classList.remove('animacionVer');
  grass.classList.remove('animacionVer');
  ground.classList.remove('animacionVer');
  ice.classList.remove('animacionVer');
  normal.classList.remove('animacionVer');
  poison.classList.remove('animacionVer');
  psychic.classList.remove('animacionVer');
  rock.classList.remove('animacionVer');
  steel.classList.remove('animacionVer');
  water.classList.remove('animacionVer');
};
const mouseOver4 = () => {
  classContenedor4.classList.add('animacionVer');
  bugw.classList.add('animacionVer');
  darkw.classList.add('animacionVer');
  dragonw.classList.add('animacionVer');
  electricw.classList.add('animacionVer');
  fairyw.classList.add('animacionVer');
  fightingw.classList.add('animacionVer');
  firew.classList.add('animacionVer');
  flyingw.classList.add('animacionVer');
  ghostw.classList.add('animacionVer');
  grassw.classList.add('animacionVer');
  groundw.classList.add('animacionVer');
  icew.classList.add('animacionVer');
  normalw.classList.add('animacionVer');
  poisonw.classList.add('animacionVer');
  psychicw.classList.add('animacionVer');
  rockw.classList.add('animacionVer');
  steelw.classList.add('animacionVer');
  waterw.classList.add('animacionVer');
};
const mouseOut4 = () => {
  classContenedor4.classList.remove('animacionVer');
  bugw.classList.remove('animacionVer');
  darkw.classList.remove('animacionVer');
  dragonw.classList.remove('animacionVer');
  electricw.classList.remove('animacionVer');
  fairyw.classList.remove('animacionVer');
  fightingw.classList.remove('animacionVer');
  firew.classList.remove('animacionVer');
  flyingw.classList.remove('animacionVer');
  ghostw.classList.remove('animacionVer');
  grassw.classList.remove('animacionVer');
  groundw.classList.remove('animacionVer');
  icew.classList.remove('animacionVer');
  normalw.classList.remove('animacionVer');
  poisonw.classList.remove('animacionVer');
  psychicw.classList.remove('animacionVer');
  rockw.classList.remove('animacionVer');
  steelw.classList.remove('animacionVer');
  waterw.classList.remove('animacionVer');
};

btn1.addEventListener('mouseover', mouseOver1);
btn2.addEventListener('mouseover', mouseOver1);
btn3.addEventListener('mouseover', mouseOver1);
btn4.addEventListener('mouseover', mouseOver1);
btn5.addEventListener('mouseover', mouseOver1);
classContenedor1.addEventListener('mouseout', mouseOut1);

btnh.addEventListener('mouseover', mouseOver2);
btn2km.addEventListener('mouseover', mouseOver2);
btn5km.addEventListener('mouseover', mouseOver2);
btn10km.addEventListener('mouseover', mouseOver2);
notInEggs.addEventListener('mouseover', mouseOver2);
classContenedor2.addEventListener('mouseout', mouseOut2);

types.addEventListener('mouseover', mouseOver3);
bug.addEventListener('mouseover', mouseOver3);
dark.addEventListener('mouseover', mouseOver3);
dragon.addEventListener('mouseover', mouseOver3);
electric.addEventListener('mouseover', mouseOver3);
fairy.addEventListener('mouseover', mouseOver3);
fighting.addEventListener('mouseover', mouseOver3);
fire.addEventListener('mouseover', mouseOver3);
flying.addEventListener('mouseover', mouseOver3);
ghost.addEventListener('mouseover', mouseOver3);
grass.addEventListener('mouseover', mouseOver3);
ground.addEventListener('mouseover', mouseOver3);
ice.addEventListener('mouseover', mouseOver3);
normal.addEventListener('mouseover', mouseOver3);
poison.addEventListener('mouseover', mouseOver3);
psychic.addEventListener('mouseover', mouseOver3);
rock.addEventListener('mouseover', mouseOver3);
steel.addEventListener('mouseover', mouseOver3);
water.addEventListener('mouseover', mouseOver3);
classContenedor3.addEventListener('mouseout', mouseOut3);

weakness.addEventListener('mouseover', mouseOver4);
bugw.addEventListener('mouseover', mouseOver4);
darkw.addEventListener('mouseover', mouseOver4);
dragonw.addEventListener('mouseover', mouseOver4);
electricw.addEventListener('mouseover', mouseOver4);
fairyw.addEventListener('mouseover', mouseOver4);
fightingw.addEventListener('mouseover', mouseOver4);
firew.addEventListener('mouseover', mouseOver4);
flyingw.addEventListener('mouseover', mouseOver4);
ghostw.addEventListener('mouseover', mouseOver4);
grassw.addEventListener('mouseover', mouseOver4);
groundw.addEventListener('mouseover', mouseOver4);
icew.addEventListener('mouseover', mouseOver4);
normalw.addEventListener('mouseover', mouseOver4);
poisonw.addEventListener('mouseover', mouseOver4);
psychicw.addEventListener('mouseover', mouseOver4);
rockw.addEventListener('mouseover', mouseOver4);
steelw.addEventListener('mouseover', mouseOver4);
waterw.addEventListener('mouseover', mouseOver4);
classContenedor4.addEventListener('mouseout', mouseOut4);